server:
  port: ${SERVER_PORT:8089}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:user-service}

  # Reactive runtime connection (R2DBC)
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5633/user_db}
    username: ${R2DBC_USERNAME:user_service}
    password: ${R2DBC_PASSWORD:UserService@2026}

  # Liquibase startup connection (JDBC)
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5633/user_db}
    username: ${JDBC_USERNAME:user_service}
    password: ${JDBC_PASSWORD:UserService@2026}

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGELOG:classpath:db/changelog/db.changelog-master.yaml}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:3s}

registration-session:
  expire-minutes: ${REGISTRATION_SESSION_EXPIRE_MINUTES:15}
reset-pin-session:
  expire-minutes: ${RESET_PIN_SESSION_EXPIRE_MINUTES:10}				

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:9090}
  realm: ${KEYCLOAK_REALM:room-system}
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:user-service}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:vhIGAwfMKvYwomnwVdyGbo7HF9IqInzn}
  client:
    client-id: ${KEYCLOAK_LOGIN_CLIENT_ID:user-login}
    client-secret: ${KEYCLOAK_LOGIN_CLIENT_SECRET:6NvGAcGrKyIhhbf0dXDLxfr1PYSWmKtE}

otp:
  expire-minutes: ${OTP_EXPIRE_MINUTES:5}
  resend-after-seconds: ${OTP_RESEND_AFTER_SECONDS:60}
  max-attempts: ${OTP_MAX_ATTEMPTS:5}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.pisethjavaschool.userservice: ${LOG_LEVEL_APP:INFO}
    com.pisethjavaschool.userservice.exception: ${LOG_LEVEL_EXCEPTION:DEBUG}
    liquibase: ${LOG_LEVEL_LIQUIBASE:INFO}
    org.springframework.boot.autoconfigure.liquibase: ${LOG_LEVEL_LIQUIBASE_AUTO:INFO}